# SQL Cheat Sheet
SUBQUERIES WITHIN FROM

- Connecting to Database

In [37]:
reload_ext sql

In [38]:
%%sql
postgresql://localhost/countries

'Connected: @countries'

In [48]:
%%sql
SELECT * FROM languages
LIMIT 2

 * postgresql://localhost/countries
   postgresql://localhost/leaders
2 rows affected.

[(1, 'AFG', 'Dari', 50.0, True), (2, 'AFG', 'Pashto', 35.0, True)]

In [47]:
%%sql
SELECT * FROM countries
LIMIT 2

 * postgresql://localhost/countries
   postgresql://localhost/leaders
2 rows affected.

[('AFG', 'Afghanistan', 'Asia', 'Southern and Central Asia', 652090.0, 1919, 'Afganistan/Afqanestan', 'Islamic Emirate', 'Kabul', 69.1761, 34.5228),
 ('NLD', 'Netherlands', 'Europe', 'Western Europe', 41526.0, 1581, 'Nederland', 'Constitutional Monarchy', 'Amsterdam', 4.89095, 52.3738)]

___

## 1. Subquery Inside FROM

- Determine the number of languagses spoken in each country in the countries table

In [56]:
%%sql
SELECT local_name, subquery.lang_count
FROM countries, 
    (SELECT code, COUNT(name) AS lang_count FROM languages
    GROUP BY code) AS subquery
WHERE countries.code = subquery.code
ORDER BY lang_count DESC

 * postgresql://localhost/countries
   postgresql://localhost/leaders
199 rows affected.

[('Zambia', 19),
 ('YeItyopÂ´iya', 16),
 ('Zimbabwe', 16),
 ('Bharat/India', 14),
 ('Nepal', 14),
 ('Mali', 13),
 ('France', 13),
 ('South Africa', 13),
 ('Malawi', 12),
 ('Angola', 12),
 ('Pakistan', 11),
 ('Panama', 11),
 ('Ghana', 11),
 ('Singapore/Singapura/Xinjiapo/Singapur', 10),
 ('Kypros/Kibris', 10),
 ('Canada', 10),
 ('Schweiz/Suisse/Svizzera/Svizra', 10),
 ('Belize', 9),
 ('Australia', 9),
 ('Zhongquo', 9),
 ('Micronesia', 9),
 ('Namibia', 9),
 ('Botswana', 9),
 ('New Zealand/Aotearoa', 9),
 ('Mocambique', 8),
 ('Sao Tome e Principe', 8),
 ('Iran', 8),
 ('Malaysia', 8),
 ('Suriya', 7),
 ('Aruba', 7),
 ('Bolivia', 7),
 ('Moldova', 7),
 ('Magyarorszag', 7),
 ('Al-Maghrib', 7),
 ('Northern Mariana Islands', 7),
 ('Senegal/Sounougal', 7),
 ('Ertra', 7),
 ('Nigeria', 6),
 ('Uganda', 6),
 ('Makedonija', 6),
 ('Belau/Palau', 6),
 ('Le Gabon', 6),
 ('Peru/Piruw', 6),
 ('Al-Jaza\x92ir/Algerie', 6),
 ('Argentina', 6),
 ('Guam', 6),
 ('Rwanda/Urwanda', 6),
 ('Burundi/Uburundi', 6),
 ('Suriname', 5),
 ('Vanuatu', 5),
 ('Â´Uman', 5),
 ('Bosna i Hercegovina', 5),
 ('Amerika Samoa', 5),
 ('Balgarija', 5),
 ('Cayman Islands', 5),
 ('Chile', 5),
 ('Trinidad and Tobago', 5),
 ('Espana', 5),
 ('The Gambia', 5),
 ('Sakartvelo', 5),
 ('Togo', 5),
 ('Eesti', 5),
 ('Guyana', 5),
 ('Xianggang/Hong Kong', 5),
 ('Al-Â´Iraq', 5),
 ('Al-Imarat al-Â´Arabiya al-Muttahida', 5),
 ('Osterreich', 5),
 ('Mauritius', 5),
 ('As-Sudan', 5),
 ('Slovenija', 5),
 ('Slovensko', 5),
 ('Republique Democratique du Congo', 5),
 ('Sesel/Seychelles', 5),
 ('Lietuva', 5),
 ('Luxembourg/Letzebuerg', 5),
 ('Muritaniya/Mauritanie', 5),
 ('Guine-Bissau', 4),
 ('Danmark', 4),
 ('Shqiperia', 4),
 ('Afganistan/Afqanestan', 4),
 ('Gibraltar', 4),
 ('Andorra', 4),
 ('Kyrgyzstan', 4),
 ('Tonga', 4),
 ('Sierra Leone', 4),
 ('Ecuador', 4),
 ('Azarbaycan', 4),
 ('Belarus', 4),
 ('Malta', 4),
 ('Tchad/Tshad', 4),
 ('Turkmenostan', 4),
 ('Hrvatska', 4),
 ('Djibouti/Jibuti', 4),
 ('Tuvalu', 4),
 ('Druk-Yul', 4),
 ('Lao', 4),
 ('Latvija', 4),
 ('Lesotho', 4),
 ('Lubnan', 4),
 ('Uzbekiston', 4),
 ('Libiya', 4),
 ('Rossija', 4),
 ('Monaco', 4),
 ('Indonesia', 4),
 ('Tanzania', 4),
 ('Island', 4),
 ('Polska', 4),
 ('Italia', 4),
 ('Al-Bahrayn', 4),
 ('Papua New Guinea/Papua Niugini', 4),
 ('Suomi', 4),
 ('Nicaragua', 4),
 ('Soomaaliya', 4),
 ('Guinea Ecuatorial', 4),
 ('Prathet Thai', 3),
 ('Hajastan', 3),
 ('Belgie/Belgique', 3),
 ('Benin', 3),
 ('Brunei Darussalam', 3),
 ('Pilipinas', 3),
 ('Foroyar', 3),
 ('Kalaallit Nunaat/Gronland', 3),
 ('Yisra\x92el/Isra\x92il', 3),
 ('Cameroun/Cameroon', 3),
 ('Kenya', 3),
 ('Centrafrique/Be-Afrika', 3),
 ('Komori/Comores', 3),
 ('Congo', 3),
 ('Liechtenstein', 3),
 ('Madagasikara/Madagascar', 3),
 ('Mexico', 3),
 ('Mongol Uls', 3),
 ('Naoero/Nauru', 3),
 ('Niger', 3),
 ('Norge', 3),
 ('Polynesie francaise', 3),
 ('Solomon Islands', 3),
 ('Sri Lanka/Ilankai', 3),
 ('Tunis/Tunisie', 3),
 ('Turkiye', 3),
 ('Ukrajina', 3),
 ('Uruguay', 3),
 ('Viet Nam', 3),
 ('United States', 3),
 ('Taehan Min\x92guk (Namhan)', 2),
 ('Costa Rica', 2),
 ('Burkina Faso', 2),
 ('Barbados', 2),
 ('Saint Lucia', 2),
 ('Antigua and Barbuda', 2),
 ('Nouvelle-Caledonie', 2),
 ('Kiribati', 2),
 ('Paraguay', 2),
 ('Cote d\x92Ivoire', 2),
 ('Bermuda', 2),
 ('Portugal', 2),
 ('Puerto Rico', 2),
 ('Marshall Islands/Majol', 2),
 ('Dhivehi Raajje/Maldives', 2),
 ('Qatar', 2),
 ('Liberia', 2),
 ('Qazaqstan', 2),
 ('Kampuchea', 2),
 ('Al-Urdunn', 2),
 ('Bangladesh', 2),
 ('Samoa', 2),
 ('Saint Vincent and the Grenadines', 2),
 ('Jamaica', 2),
 ('kaNgwane', 2),
 ('Ireland/Eire', 2),
 ('Honduras', 2),
 ('Tocikiston', 2),
 ('Haiti/Dayti', 2),
 ('Ellada', 2),
 ('Guatemala', 2),
 ('Grenada', 2),
 ('El Salvador', 2),
 ('Misr', 2),
 ('Al-Kuwayt', 2),
 ('Venezuela', 2),
 ('The Bahamas', 2),
 ('Dominica', 2),
 ('Myanma Pye', 1),
 ('Sverige', 1),
 ('Saint Kitts and Nevis', 1),
 ('Deutschland', 1),
 ('Cuba', 1),
 ('San Marino', 1),
 ('Al-Â´Arabiya as-SaÂ´udiya', 1),
 ('Choson Minjujuui InÂ´min Konghwaguk (Bukhan)', 1),
 ('Colombia', 1),
 ('Al-Yaman', 1),
 ('Nihon/Nippon', 1),
 ('Guinee', 1),
 ('Republica Dominicana', 1),
 ('The Turks and Caicos Islands', 1),
 ('Nederland', 1),
 ('United Kingdom', 1),
 ('Brasil', 1)]

____

In [5]:
%%sql
postgresql://localhost/leaders

'Connected: @leaders'

In [24]:
%%sql
SELECT * FROM states

   postgresql://localhost/countries
 * postgresql://localhost/leaders
13 rows affected.

[('Australia', 'Oceania', 1901, 1.88, 32.74),
 ('Brunei', 'Asia', 1984, 1.96, 6.06),
 ('Chile', 'South America', 1810, 1.8, 15.82),
 ('Egypt', 'Africa', 1922, 2.7, 14.9),
 ('Haiti', 'North America', 1804, 3.03, 2.74),
 ('India', 'Asia', 1947, 2.43, 11.58),
 ('Liberia', 'Africa', 1847, 4.64, 11.65),
 ('Norway', 'Europe', 1905, 1.93, 39.6),
 ('Oman', 'Asia', 1951, 2.75, 8.82),
 ('Portugal', 'Europe', 1143, 1.31, 34.8),
 ('Spain', 'Europe', 1492, 1.53, 38.64),
 ('Uruguay', 'South America', 1828, 2.03, 22.31),
 ('Vietnam', 'Asia', 1945, 1.7, 24.0)]

In [23]:
%%sql
SELECT * FROM monarchs

   postgresql://localhost/countries
 * postgresql://localhost/leaders
4 rows affected.

[('Brunei', 'Asia', 'Hassanal Bolkiah'),
 ('Oman', 'Asia', 'Qaboos bin Said al Said'),
 ('Norway', 'Europe', 'Harald V'),
 ('Spain', 'Europe', 'Felipe VI')]

___

- Max percentage of women in parliament  for each continent in the states table

In [20]:
%%sql
SELECT continent, MAX(women_parli_perc) AS max_perc
FROM states
GROUP BY continent
ORDER BY continent

   postgresql://localhost/countries
 * postgresql://localhost/leaders
6 rows affected.

[('Africa', 14.9),
 ('Asia', 24.0),
 ('Europe', 39.6),
 ('North America', 2.74),
 ('Oceania', 32.74),
 ('South America', 22.31)]

- Max percentage of women in parliament  for each continent in the monarchs table

In [34]:
%%sql
SELECT DISTINCT monarchs.continent, subquery.max_perc
FROM monarchs, 
    (SELECT continent, MAX(women_parli_perc) AS max_perc
    FROM states
    GROUP BY continent) AS subquery
WHERE monarchs.continent = subquery.continent
ORDER BY continent;

   postgresql://localhost/countries
 * postgresql://localhost/leaders
2 rows affected.

[('Asia', 24.0), ('Europe', 39.6)]

___